on:
  workflow_dispatch:
    inputs:
      fmrVersion:
        description: 'FMR version'
        required: true
        type: string

jobs:
  build_and_push:
    name: Build and push the container
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/yrosemacbs
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/yrosemacbs/fmr:${{ fmrVersion }}
          build-args: |
            "FMR_VERSION=${{ fmrVersion }}"
