on:
  workflow_dispatch:

env:
  FMR_VERSION: latest

jobs:
  build_and_push:
    name: Build and push the container
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/yrosemacbs
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/yrosemacbs/fmr:${{ FMR_VERSION }}
          build-args: |
            "FMR_VERSION=${{ FMR_VERSION }}"
